version: '3'
services:
  
  prisma:
    image: prismagraphql/prisma:1.16
    ports: 
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: thehouseisalwaysblue
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - ./postgres:/var/lib/postgresql/data


volumes:
  rabbitmq_data:
    driver: local